[package]
name = "teloxide-test-bot"
version = "0.1.0"
authors = ["Orin Serimon <orin220444@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
teloxide = "0.3"
rusqlite = "0.24"
teloxide-macros = "0.3"
dotenv = "0.15.0"
log = "0.4"
pretty_env_logger = "0.4.0"
arquery = "0.1.0"
[dependencies.tokio]
version =  "0.2.11"
features = ["full"]
[dependencies.reqwest]
version = "0.10.8"
features = ["json"]
[dependencies.mongodb]
version = "1.1.1"
default_features = false
features = ["tokio-runtime"]

#dotenv_codegen = "0.15.0"
